const fs = require('fs');
const path = require('path');

const mockDbPath = path.join(__dirname, '..', 'src', 'services', 'mockDb.ts');
let mockDbContent = fs.readFileSync(mockDbPath, 'utf8');

// Read the processed products array from the generated file or rebuild it here to ensure it's exact
const estoqueCsv = `AÇÚCAR MASCAVO;10;0;0;10
AÇÚCAR REFINADO;25;0;0;25
ALHO EM PÓ KG;25;0;0;25
ALHO TORRADO;0;0;0;0
AMIDO DE MILHO KG;0;0;0;0
ARROZ PARBOLIZADO KG;0;0;0;0
AVEIA  KG;0;0;0;0
AZEITE 5 L;0;0;0;0
BARRA CHOC. MEIO AMARGO;0;0;0;0
BARRA CHOC. AO LEITE;0;0;0;0
BATATA FARM CX (6UN 2KG) ;13;15;6;22
CACAU EM PÓ 100% 500G;0;0;0;0
CALDA MORANGO;0;0;0;0
CALDO DE CARNE 1KG;0;0;0;0
CALDO LEGUMES 1KG;0;0;0;0
CANELA EM PÓ;0;0;0;0
CARNE SECA DESF;0;0;0;0
CASTANHA CAJU 500G;0;0;0;0
CASTANHA PARÁ 500G;0;0;0;0
CEBOLA EM PÓ;10;0;0;10
CHIMICHURRI 500g;20;0;0;20
COCO RALADO;0;0;0;0
COSTELA BOVINA;12;0;0;12
COSTELA SUÍNA;0;0;0;0
CRAVO DA ÍNDIA;0;0;0;0
CREAM CHEESE ;0;0;0;0
CREME DE LEITE;0;0;0;0
DADINHO TAPIOCA 180G (PORÇÃO);0;0;0;0
DELICIA DE CHOCOLATE;0;0;0;0
DEMI GLACE 1KG;15;0;0;15
DOCE DE LEITE;0;0;0;0
DOMEC 1 LITRO;0;0;0;0
FARINHA MANDIOCA;0;0;0;0
FARINHA TRIGO;0;0;0;0
FARINHA TEMPERADA ;0;0;0;0
FEIJÃO DE CORDA;0;0;0;0
FEIJÃO PRETO;0;0;0;0
FUMAÇA;6;0;0;6
GELEIA PIMENTA 1,2KG;25;0;0;25
GOMA DE TAPIOCA;0;0;0;0
GRÃO DE BICO;0;0;0;0
KETCHUP;0;0;0;0
LEITE CONDENSADO LATA;0;0;0;0
LEITE INTEGRAL 1L ;0;0;0;0
LEMON PEPPER ;20;0;0;20
LICOR;0;0;0;0
LINGUIÇA CALABRESA KG;0;0;0;0
LINGUIÇA TOSCANA;0;0;0;0
LOURO EM PÓ;15;0;0;15
MACARRÃO ;0;0;0;0
MAIONESE ;0;0;0;0
MANTEIGA GARRAFA;0;0;0;0
MEL GARRAFA;0;0;0;0
MILHO VERDE LATA;0;0;0;0
MOLHO DE TOMATE 4,1KG;0;0;0;0
MOLHO INGLÊS;0;0;0;0
MOSTARDA HEINZ;0;0;0;0
MOSTARDA EM GRÃOS;25;0;0;25
NOZ MOSCADA 200g;18;0;0;18
NUTELLA 3KG;0;0;0;0
ÓLEO DE ALGODÃO ;0;0;0;0
ORÉGANO;15;0;0;15
OVOMALTINE 750G;0;0;0;0
PANKO;0;0;0;0
PÁPRICA DEFUMADA;20;0;0;20
PÁPRICA DOCE;20;0;0;20
PÁPRICA PICANTE;20;0;0;20
PICLES BALDE;5;0;0;5
PICLES HEMMER 800G;0;0;0;0
PIMENTA CAIENA;20;0;0;20
PIMENTA DO REINO;25;0;0;25
PUDIM;0;0;0;0
R005;0;0;0;0
R006;0;0;0;0
R007;0;0;0;0
RUBACÃO ;0;0;0;0
SAL REFINADO;20;0;0;20
SAL BLEND;0;0;0;0
SHOYU;0;0;0;0
STROGONOF 150G;0;0;0;0
TAPIOCA FLOCADA;0;0;0;0
TOMATE PELATI 2,5KG;0;0;0;0
VINAGRE;0;0;0;0
VINAGRE MAÇÃ;0;0;0;0
VINHO BRANCO;0;0;0;0
VINHO TINTO;0;0;0;0
ACÉM;0;0;0;0
AIPIM;0;0;0;0
BABY BEEF;0;0;0;0
BACON FATIADO;0;0;0;0
BACON MANTA ;0;0;0;0
BALDE MANTEIGA;0;0;0;0
BALDE MARGARINA 3KG;0;0;0;0
BARBECUE 1KG;0;0;0;0
BATATA CX;0;0;0;0
BATATA PALHA ;0;0;0;0
CARRÉ;0;0;0;0
CHEDDAR;0;0;0;0
COXA SOBRECOXA;0;0;0;0
FILÉ DE FRANGO;0;0;0;0
FILÉ DE SOBRECOXA;0;0;0;0
FILÉ DE PEITO;0;0;0;0
FRALDINHA;0;0;0;0
GOUDAN;0;0;0;0
LOMBO;0;0;0;0
PATINHO;0;0;0;0
QUEIJO MONTANHÊS;0;0;0;0
QUEIJO PARMESÃO;0;0;0;0
REQUEIJÃO CREMOSO UN;0;0;0;0
BALDE ÓLEO;0;0;0;0
ÁLCOOL GARRAFA;0;0;0;0
ÁLCOOL P/MÃOS;0;0;0;0
BAUNILHA;0;0;0;0
BICO DE MAÇARICO;0;0;0;0
BOBINA GRANDE;0;0;0;0
BOBINA PEQUENA;0;0;0;0
BOBINA IMPRESSORA;0;0;0;0
CANETA;0;0;0;0
CANUDO PCT;0;0;0;0
COLHER DESCARTÁVEL PACOTE;0;0;0;0
COPO DESCARTÁVEL;0;0;0;0
DESENGRAXANTE 5L;0;0;0;0
DESINCRUSTANTE 5L;0;0;0;0
DESINFETANTE HORT;0;0;0;0
DETERGENTE CLORADO;0;0;0;0
ESPONJA;0;0;0;0
FIBRAÇO;0;0;0;0
FILME PVC;0;0;0;0
GRAMPEADOR;0;0;0;0
GRAMPO;0;0;0;0
LUVA AMERELA G;0;0;0;0
LUVA AMERELA M;0;0;0;0
LUVA AZUL;0;0;0;0
LUVA PRETA;0;0;0;0
LUVA RANHADURA G;0;0;0;0
LUVA VERDE;0;0;0;0
MAÇARICO;0;0;0;0
MARCA TEXTO;0;0;0;0
MÁSCARA AZUL;0;0;0;0
ÓCULOS PROTETOR;0;0;0;0
PÁ DE LIXO;0;0;0;0
PANO DE CHÃO;0;0;0;0
PAPEL HIGIÊNICO;0;0;0;0
PAPEL TOALHA;0;0;0;0
PERFEX G;0;0;0;0
PILOTO;0;0;0;0
RODO;0;0;0;0
SABÃO NEUTRO 5L;0;0;0;0
SABÃO P/MÃOS;0;0;0;0
SACO LIXO 100 C/100UN;0;0;0;0
SACO LIXO 200 C/100UN;0;0;0;0
SACO LIXO PRETO 300;0;0;0;0
TOUCA;0;0;0;0
VASSOURA;0;0;0;0`;

const producaoCsv = `AÇÚCAR MASCAVO kg;20
AÇÚCAR REFINADO kg;40
ALHO EM PÓ KG;8
ALHO TORRADO 500g;12
AMIDO DE MILHO KG;30
ANA MARIA;0
ARROZ PARBOLIZADO KG;510
AVEIA  KG;10
AZEITE 5L;4
BACON MANTA KG;80
BALDE MANTEIGA;2
BARBECUE 1KG;48
BARRA CHOC. AO LEITE;3
BARRA CHOC. MEIO AMARGO;6
BASE MILK SHAKE;12
BATATA FARM CX (6UN 2KG) ;145
BISCOITO MAISENA;50
BLEND CARNE;4488
BLEND FALAFEL 90G;108
BLEND FRANGO 90G;216
BLEND PEIXE UNI;216
BLEND QUEIJO UNI;324
BLEND VACOMBINHO 60G;432
BOLINHO CARNE SECA ;2000
BOLINHO COSTELA;2000
BOMBOM 150G;54
BOX Y029 C/100;140
BROWNIE LUIZ;270
CACAU EM PÓ 100% 500G;2
CAFÉ 500G;6
CALDA MORANGO;5
CALDO DE CARNE 1KG;20
CALDO LEGUMES 1KG;20
CANELA EM PÓ;2
CANUDO PCT;32
CARNE SECA DESF;20
CASTANHA CAJU 500G;2
CASTANHA PARÁ 500G;2
CEBOLA EM PÓ;10
CHEDDAR UN;2592
CHIMICHURRI 500g;10
COCO RALADO;20
COPO VACA AVELUDADA C/40;54
COPO VACA MALTADA C/40;54
COPO VACA RAIZ C/40;54
COPO VACA VERMELHA C/40;54
COSTELA BOVINA;160
COSTELA SUÍNA;60
CRAVO DA ÍNDIA;2
CREAM CHEESE ;32
CREME DE LEITE;120
DADINHO TAPIOCA 180G (PORÇÃO);432
DEL VALLE LARANJA 18UN;6
DEL VALLE UVA 18UN;6
DELICIA DE CHOCOLATE;324
DEMI GLACE 1KG;10
DOCE DE LEITE;40
DOMEC 1 LITRO;40
EMB BATATA F012;5400
EMB FRANCROQUITOS 100UNI;65
EMB QUEIJO GOUDAN 100UN;130
EMB R005;4400
EMB R006;4400
EMB R007;4400
ESTIQUETA HAMB DUPLO;16
ESTIQUETA S/ALFACE;16
ETIQUETA S/CEBOLA ROLOS;16
ETIQUETA S/MOLHO ROLOS;16
ETIQUETA S/PICLES;16
ETIQUETA S/QUEIJO;16
ETIQUETA S/TOMATE ROLOS;16
ETIQUETA USAR PRIMEIRO ROLOS;16
EXTRATO TOMATE 1,7;40
FARELO OREO UNI;216
FARINHA MANDIOCA;20
FARINHA TEMPERADA ;60
FARINHA TRIGO;60
FEIJÃO DE CORDA;200
FEIJÃO PRETO;120
FRANCROC 500un;0
FRANCROC CRUNCH;324
FRANCROC ITALIANO;324
FRANCROC Q/SALADA 500un;0
FRANCROC QUEIJO 500un;0
FUMAÇA;4
GELEIA PIMENTA 1,2KG;20
GOMA DE TAPIOCA;60
GOUDA;1728
GRAMPO;32
GRÃO DE BICO;40
ISCA DE PEIXE;40
KETCHUP;64
LACRE BAIÃO;12
LACRE VACA;12
LEITE CONDENSADO LATA;160
LEITE INTEGRAL 1L ;40
LEMON PEPPER ;10
LICOR;32
LINGUIÇA CALABRESA KG;100
LINGUIÇA TOSCANA;30
LOMBO;120
LOURO EM PÓ;2
LUVA PRETA;48
MACARRÃO ;200
MAIONESE ;80
MANTEIGA GARRAFA;24
MARMITA C/TAMPA (100 UND);12
MÁSCARA AZUL;8
MEL GARRAFA;20
MILHO VERDE LATA;80
MOLHO DE TOMATE 4,1KG;80
MOLHO INGLÊS;40
MOSTARDA EM GRÃOS;6
MOSTARDA HEINZ;20
NOZ MOSCADA 200g;2
NUGGET 2,5KG;65
NUTELLA 3KG;20
NUTELLA 650G;20
ÓLEO DE ALGODÃO ;120
ORÉGANO;4
OVOMALTINE 750G;10
PANKO;120
PÃO BOLA PCT;356
PÃO SMART PCT;1426
PÃO SUPREMO PCT;1782
PAPEL TOALHA;8
PÁPRICA DEFUMADA;10
PÁPRICA DOCE;10
PÁPRICA PICANTE;10
PEIXE VACA;216
PICLES BALDE;24
PICLES HEMMER 800G;60
PIMENTA CAIENA;2
PIMENTA DO REINO;10
POTE P/MOLHO;4400
PUDIM;216
QUEIJO COALHO UM;432
QUEIJO MONTANHÊS;20
QUEIJO PRATO;2592
REQUEIJÃO CREMOSO UN;216
RUBACÃO ;40
SACO DE GELO;200
SACO VÁCUO G 500un;3
SACO VÁCUO M 500un;3
SACO VÁCUO P 500un;3
SACOLA BAIÃO G 250 UNI;3
SACOLA BAIÃO M 250 UNI;3
SACOLA VACA G 250UN;11
SACOLA VACA P 250UN;11
SAL BLEND;20
SAL REFINADO;20
SHOYU;40
SÓ VACA 1000 UN;0
SÓ VACA 500 UN;0
STROGONOF 150G;216
SUPORTE DE COPO MILK;108
TALHER DESCARTÁVEL 50UN;64
TAMPA COPO MILK;216
TAMPA V051;4400
TAPIOCA FLOCADA;20
TEMP VACA 33G;200
TOMATE PELATI 2,5KG;20
VACA CRUNCH 500un;0
VACA DERRETIDA 1000UN;0
VACA DERRETIDA 500un;0
VACA E O PORCO 1000UN;0
VACA E O PORCO 500un;0
VACA FAROFEIRA 500un;0
VACA NO PASTO 500un;0
VACA QUEIJADA 1000UN;0
VACA QUEIJADA 500un;0
VACA SEM VACA 500un;0
VACA SUPREMA 1000UN;0
VACA SUPREMA 500un;0
VACACAU 500un;0
VACARIOCÃO 500un;0
VACOMBINHO 100un;0
VACOSTELA 1000UN;0
VACOSTELA 500un;0
VACOSTELA UNI;432
VAQUINHAS VACOMBINHO;432
VINAGRE;40
VINAGRE MAÇÃ;40
VINHO BRANCO;24
VINHO TINTO;24
XODÓ;324`;

const nameMap = {
  'AÇÚCAR MASCAVO': 'AÇÚCAR MASCAVO',
  'AÇÚCAR MASCAVO kg': 'AÇÚCAR MASCAVO',
  'AÇÚCAR REFINADO': 'AÇÚCAR REFINADO',
  'AÇÚCAR REFINADO kg': 'AÇÚCAR REFINADO',
  'ALHO EM PÓ KG': 'ALHO EM PÓ',
  'ALHO EM PÓ': 'ALHO EM PÓ',
  'ALHO TORRADO': 'ALHO TORRADO',
  'ALHO TORRADO 500g': 'ALHO TORRADO',
  'AMIDO DE MILHO KG': 'AMIDO DE MILHO',
  'AMIDO DE MILHO': 'AMIDO DE MILHO',
  'ARROZ PARBOLIZADO KG': 'ARROZ PARBOILIZADO',
  'ARROZ PARBOILIZADO': 'ARROZ PARBOILIZADO',
  'AVEIA  KG': 'AVEIA',
  'AVEIA': 'AVEIA',
  'AZEITE 5 L': 'AZEITE 5L',
  'AZEITE 5L': 'AZEITE 5L',
  'BARRA CHOC. MEIO AMARGO': 'CHOCOLATE MEIO AMARGO',
  'BARRA CHOC. AO LEITE': 'CHOCOLATE AO LEITE',
  'BATATA FARM CX (6UN 2KG)': 'BATATA FARM CX',
  'BATATA FARM CX (6UN 2KG) ': 'BATATA FARM CX',
  'CACAU EM PÓ 100% 500G': 'CACAU EM PÓ 100%',
  'CALDA MORANGO': 'CALDA DE MORANGO',
  'CALDO DE CARNE 1KG': 'CALDO DE CARNE 1KG',
  'CALDO LEGUMES 1KG': 'CALDO LEGUMES 1KG',
  'CANELA EM PÓ': 'CANELA EM PÓ',
  'CARNE SECA DESF': 'CARNE SECA DESF 1KG',
  'CASTANHA CAJU 500G': 'CASTANHA DE CAJU',
  'CASTANHA PARÁ 500G': 'CASTANHA DO PARÁ',
  'CEBOLA EM PÓ': 'CEBOLA EM PÓ',
  'CHIMICHURRI 500g': 'CHIMICHURRI',
  'COCO RALADO': 'COCO RALADO',
  'COSTELA BOVINA': 'COSTELA BOVINA DESF 1KG',
  'COSTELA BOVINA DESF 1KG': 'COSTELA BOVINA DESF 1KG',
  'COSTELA SUÍNA': 'COSTELA SUÍNA DESF 1KG',
  'CRAVO DA ÍNDIA': 'CRAVO DA ÍNDIA',
  'CREAM CHEESE ': 'CREAM CHEESE',
  'CREAM CHEESE': 'CREAM CHEESE',
  'CREME DE LEITE': 'CREME DE LEITE',
  'DADINHO TAPIOCA 180G (PORÇÃO)': 'DADINHO DE TAPIOCA',
  'DELICIA DE CHOCOLATE': 'DELICIA DE CHOCOLATE',
  'DEMI GLACE 1KG': 'DEMI GLACE 1KG',
  'DOCE DE LEITE': 'DOCE DE LEITE',
  'DOMEC 1 LITRO': 'DOMEC 1L',
  'FARINHA MANDIOCA': 'FARINHA DE MANDIOCA',
  'FARINHA TRIGO': 'FARINHA DE TRIGO',
  'FARINHA TEMPERADA ': 'FARINHA TEMPERADA',
  'FARINHA TEMPERADA': 'FARINHA TEMPERADA',
  'FEIJÃO DE CORDA': 'FEIJÃO DE CORDA',
  'FEIJÃO PRETO': 'FEIJÃO PRETO',
  'FUMAÇA': 'FUMAÇA LÍQUIDA',
  'GELEIA PIMENTA 1,2KG': 'GELEIA DE PIMENTA 1.2KG',
  'GOMA DE TAPIOCA': 'GOMA DE TAPIOCA',
  'GRÃO DE BICO': 'GRÃO DE BICO',
  'KETCHUP': 'KETCHUP',
  'LEITE CONDENSADO LATA': 'LEITE CONDENSADO',
  'LEITE INTEGRAL 1L ': 'LEITE INTEGRAL 1L',
  'LEITE INTEGRAL 1L': 'LEITE INTEGRAL 1L',
  'LEMON PEPPER ': 'LEMON PEPPER',
  'LEMON PEPPER': 'LEMON PEPPER',
  'LICOR': 'LICOR',
  'LINGUIÇA CALABRESA KG': 'LINGUIÇA CALABRESA',
  'LINGUIÇA TOSCANA': 'LINGUIÇA TOSCANA',
  'LOURO EM PÓ': 'LOURO EM PÓ',
  'MACARRÃO ': 'MACARRÃO',
  'MACARRÃO': 'MACARRÃO',
  'MAIONESE ': 'MAIONESE',
  'MAIONESE': 'MAIONESE',
  'MANTEIGA GARRAFA': 'MANTEIGA DE GARRAFA',
  'MEL GARRAFA': 'MEL',
  'MILHO VERDE LATA': 'MILHO VERDE',
  'MOLHO DE TOMATE 4,1KG': 'MOLHO DE TOMATE 4.1KG',
  'MOLHO INGLÊS': 'MOLHO INGLÊS',
  'MOSTARDA HEINZ': 'MOSTARDA HEINZ',
  'MOSTARDA EM GRÃOS': 'MOSTARDA EM GRÃOS',
  'NOZ MOSCADA 200g': 'NOZ MOSCADA',
  'NUTELLA 3KG': 'NUTELLA 3KG',
  'NUTELLA 650G': 'NUTELLA 650G',
  'ÓLEO DE ALGODÃO ': 'ÓLEO DE ALGODÃO',
  'ÓLEO DE ALGODÃO': 'ÓLEO DE ALGODÃO',
  'ORÉGANO': 'ORÉGANO',
  'OVOMALTINE 750G': 'OVOMALTINE 750G',
  'PANKO': 'FARINHA PANKO',
  'PÁPRICA DEFUMADA': 'PÁPRICA DEFUMADA',
  'PÁPRICA DOCE': 'PÁPRICA DOCE',
  'PÁPRICA PICANTE': 'PÁPRICA PICANTE',
  'PICLES BALDE': 'PICLES EM CONSERVA (BALDE)',
  'PICLES HEMMER 800G': 'PICLES HEMMER 800G',
  'PIMENTA CAIENA': 'PIMENTA CAIENA',
  'PIMENTA DO REINO': 'PIMENTA DO REINO',
  'SAL REFINADO': 'SAL REFINADO',
  'SAL BLEND': 'SAL BLEND',
  'SHOYU': 'SHOYU',
  'TAPIOCA FLOCADA': 'TAPIOCA FLOCADA',
  'TOMATE PELATI 2,5KG': 'TOMATE PELATI 2.5KG',
  'VINAGRE': 'VINAGRE',
  'VINAGRE MAÇÃ': 'VINAGRE DE MAÇÃ',
  'VINHO BRANCO': 'VINHO BRANCO',
  'VINHO TINTO': 'VINHO TINTO',
  'ACÉM': 'ACÉM',
  'AIPIM': 'AIPIM',
  'BABY BEEF': 'BABY BEEF',
  'BACON FATIADO': 'BACON FATIADO 1KG',
  'BACON MANTA ': 'BACON MANTA 1KG',
  'BACON MANTA': 'BACON MANTA 1KG',
  'BACON MANTA KG': 'BACON MANTA 1KG',
  'BALDE MANTEIGA': 'MANTEIGA (BALDE)',
  'BALDE MARGARINA 3KG': 'MARGARINA (BALDE)',
  'BARBECUE 1KG': 'MOLHO BARBECUE',
  'BATATA CX': 'BATATA CX',
  'BATATA PALHA ': 'BATATA PALHA',
  'BATATA PALHA': 'BATATA PALHA',
  'CARRÉ': 'CARRÉ',
  'CHEDDAR': 'QUEIJO CHEDDAR FATIADO',
  'CHEDDAR UN': 'QUEIJO CHEDDAR FATIADO',
  'COXA SOBRECOXA': 'COXA SOBRECOXA',
  'FILÉ DE FRANGO': 'FILÉ DE FRANGO',
  'FILÉ DE SOBRECOXA': 'FILÉ DE SOBRECOXA',
  'FILÉ DE PEITO': 'FILÉ DE PEITO',
  'FRALDINHA': 'FRALDINHA',
  'GOUDAN': 'QUEIJO GOUDAN',
  'GOUDA': 'QUEIJO GOUDA',
  'LOMBO': 'LOMBO',
  'PATINHO': 'PATINHO',
  'QUEIJO MONTANHÊS': 'QUEIJO MONTANHÊS',
  'QUEIJO PARMESÃO': 'QUEIJO PARMESÃO',
  'REQUEIJÃO CREMOSO UN': 'REQUEIJÃO CREMOSO',
  'BALDE ÓLEO': 'ÓLEO (BALDE)',
  'ÁLCOOL GARRAFA': 'ÁLCOOL EM GARRAFA',
  'ÁLCOOL P/MÃOS': 'ÁLCOOL EM GEL',
  'BAUNILHA': 'ESSÊNCIA DE BAUNILHA',
  'BICO DE MAÇARICO': 'BICO DE MAÇARICO',
  'BOBINA GRANDE': 'BOBINA GRANDE',
  'BOBINA PEQUENA': 'BOBINA PEQUENA',
  'BOBINA IMPRESSORA': 'BOBINA IMPRESSORA',
  'CANETA': 'CANETA',
  'CANUDO PCT': 'CANUDO (PACOTE)',
  'COLHER DESCARTÁVEL PACOTE': 'COLHER DESCARTÁVEL',
  'COPO DESCARTÁVEL': 'COPO DESCARTÁVEL',
  'DESENGRAXANTE 5L': 'DESENGRAXANTE 5L',
  'DESINCRUSTANTE 5L': 'DESINCRUSTANTE 5L',
  'DESINFETANTE HORT': 'DESINFETANTE HORTIFRUTI',
  'DETERGENTE CLORADO': 'DETERGENTE CLORADO',
  'ESPONJA': 'ESPONJA',
  'FIBRAÇO': 'ESPONJA FIBRAÇO',
  'FILME PVC': 'FILME PVC',
  'GRAMPEADOR': 'GRAMPEADOR',
  'GRAMPO': 'GRAMPO',
  'LUVA AMERELA G': 'LUVA AMARELA G',
  'LUVA AMERELA M': 'LUVA AMARELA M',
  'LUVA AZUL': 'LUVA AZUL',
  'LUVA PRETA': 'LUVA PRETA',
  'LUVA RANHADURA G': 'LUVA RANHADURA G',
  'LUVA VERDE': 'LUVA VERDE',
  'MAÇARICO': 'MAÇARICO',
  'MARCA TEXTO': 'MARCA TEXTO',
  'MÁSCARA AZUL': 'MÁSCARA AZUL',
  'ÓCULOS PROTETOR': 'ÓCULOS PROTETOR',
  'PÁ DE LIXO': 'PÁ DE LIXO',
  'PANO DE CHÃO': 'PANO DE CHÃO',
  'PAPEL HIGIÊNICO': 'PAPEL HIGIÊNICO',
  'PAPEL TOALHA': 'PAPEL TOALHA',
  'PERFEX G': 'PERFEX G',
  'PILOTO': 'PILOTO',
  'RODO': 'RODO',
  'SABÃO NEUTRO 5L': 'SABÃO NEUTRO 5L',
  'SABÃO P/MÃOS': 'SABÃO PARA MÃOS',
  'SACO LIXO 100 C/100UN': 'SACO DE LIXO 100L',
  'SACO LIXO 200 C/100UN': 'SACO DE LIXO 200L',
  'SACO LIXO PRETO 300': 'SACO DE LIXO 300L',
  'TOUCA': 'TOUCA DESCARTÁVEL',
  'VASSOURA': 'VASSOURA',
  
  // Additional items from Central de Produção that need standard names
  'BLEND CARNE': 'BLEND CARNE 150G',
  'BLEND FALAFEL 90G': 'BLEND FALAFEL 90G',
  'BLEND FRANGO 90G': 'BLEND FRANGO 90G',
  'BLEND PEIXE UNI': 'BLEND PEIXE',
  'BLEND QUEIJO UNI': 'BLEND QUEIJO',
  'BLEND VACOMBINHO 60G': 'BLEND VACOMBINHO 60G',
  'BOLINHO CARNE SECA ': 'BOLINHO DE CARNE SECA',
  'BOLINHO COSTELA': 'BOLINHO DE COSTELA',
  'BOMBOM 150G': 'BOMBOM DE CHOCOLATE',
  'BOX Y029 C/100': 'BOX EMBALAGEM Y029',
  'BROWNIE LUIZ': 'BROWNIE DO LUIZ',
  'EMB BATATA F012': 'EMBALAGEM BATATA F012',
  'EMB FRANCROQUITOS 100UNI': 'EMBALAGEM FRANCROQUITOS',
  'EMB QUEIJO GOUDAN 100UN': 'EMBALAGEM QUEIJO GOUDAN',
  'EMB R005': 'EMBALAGEM R005',
  'EMB R006': 'EMBALAGEM R006',
  'EMB R007': 'EMBALAGEM R007',
  'PÃO BOLA PCT': 'PÃO BOLA',
  'PÃO SMART PCT': 'PÃO SMART',
  'PÃO SUPREMO PCT': 'PÃO SUPREMO',
  'QUEIJO COALHO UM': 'QUEIJO COALHO',
  'SACOLA BAIÃO G 250 UNI': 'SACOLA BAIÃO G',
  'SACOLA BAIÃO M 250 UNI': 'SACOLA BAIÃO M',
  'SACOLA VACA G 250UN': 'SACOLA VACA G',
  'SACOLA VACA P 250UN': 'SACOLA VACA P',
  'TALHER DESCARTÁVEL 50UN': 'TALHER DESCARTÁVEL',
  'TAMPA COPO MILK': 'TAMPA COPO MILKSHAKE',
  'TAMPA V051': 'TAMPA V051',
  'TEMP VACA 33G': 'TEMPERO VACA 33G',
  'VACOSTELA UNI': 'VACOSTELA',
  'VAQUINHAS VACOMBINHO': 'VAQUINHAS VACOMBINHO',
  'XODÓ': 'SOBREMESA XODÓ'
};

const defaultUnit = (name) => {
  const clean = name.toLowerCase();
  if (clean.includes('kg') || clean.includes('g') || clean.includes('quilo')) return 'kg';
  if (clean.includes(' litr') || clean.includes(' 5l') || clean.includes(' 1l') || clean.includes(' óleo') || clean.includes(' vinagre')) return 'litro';
  if (clean.includes(' cx') || clean.includes(' caixa')) return 'caixa';
  if (clean.includes(' pct') || clean.includes(' pacote') || clean.includes(' saco')) return 'pacote';
  return 'unidade';
};

// Process products from Controle de Estoque
const parsedProducts = [];
const lines = estoqueCsv.trim().split('\n');

lines.forEach(line => {
  const parts = line.split(';');
  if (parts.length < 5) return;
  const rawName = parts[0].trim();
  const initialStock = Number(parts[1]) || 0;
  const entries = Number(parts[2]) || 0;
  const exits = Number(parts[3]) || 0;
  const finalStock = Number(parts[4]) || 0;
  
  const officialName = nameMap[rawName] || rawName;
  const unit = defaultUnit(rawName);

  parsedProducts.push({
    id: `prod-${parsedProducts.length + 1}`,
    name: officialName,
    unit: unit,
    initialStock: initialStock,
    entries: entries,
    exits: exits,
    finalStock: finalStock
  });
});

// Process production from central de produção
const centralLines = producaoCsv.trim().split('\n');
const productionMap = {};

centralLines.forEach(line => {
  const parts = line.split(';');
  if (parts.length < 2) return;
  const rawName = parts[0].trim();
  const quantity = Number(parts[1]) || 0;
  if (quantity === 0) return; // Skip zero items for central list

  const officialName = nameMap[rawName] || rawName;
  productionMap[officialName] = quantity;
});

// For any items in central list that weren't in the stock CSV, add them with 0 stock
const existingNames = new Set(parsedProducts.map(p => p.name));
Object.keys(productionMap).forEach(name => {
  if (!existingNames.has(name)) {
    parsedProducts.push({
      id: `prod-${parsedProducts.length + 1}`,
      name: name,
      unit: defaultUnit(name),
      initialStock: 0,
      entries: 0,
      exits: 0,
      finalStock: 0
    });
  }
});

// Build the mockDb.ts content with new values
mockDbContent = fs.readFileSync(mockDbPath, 'utf8');

// Replace Product interface to include productionTarget?
mockDbContent = mockDbContent.replace(
  `export interface Product {
  id: string;
  name: string;
  unit: string;
  initialStock: number;
  entries: number;
  exits: number;
  finalStock: number; // calculated: initialStock + entries - exits
}`,
  `export interface Product {
  id: string;
  name: string;
  unit: string;
  initialStock: number;
  entries: number;
  exits: number;
  finalStock: number;
  productionTarget?: number;
}`
);

// Map products to include productionTarget values
const productsWithTarget = parsedProducts.map(p => {
  const target = productionMap[p.name] || 0;
  if (target > 0) {
    return { ...p, productionTarget: target };
  }
  return p;
});

// Replace INITIAL_PRODUCTS block
const startMarker = 'const INITIAL_PRODUCTS: Product[] = [';
const endMarker = '];\n\nconst INITIAL_MOVEMENTS';

const startIndex = mockDbContent.indexOf(startMarker);
const endIndex = mockDbContent.indexOf(endMarker, startIndex);

if (startIndex !== -1 && endIndex !== -1) {
  const productsStr = JSON.stringify(productsWithTarget, null, 2);
  mockDbContent = 
    mockDbContent.substring(0, startIndex) +
    `const INITIAL_PRODUCTS: Product[] = ${productsStr}` +
    mockDbContent.substring(endIndex);
}

// Update mockDb.init() reset migration check to clean up old small DB and reset with the 222 items list
mockDbContent = mockDbContent.replace(
  `  init() {
    if (!localStorage.getItem(STORAGE_KEYS.PRODUCTS)) {
      localStorage.setItem(STORAGE_KEYS.PRODUCTS, JSON.stringify(INITIAL_PRODUCTS));
    }
    if (!localStorage.getItem(STORAGE_KEYS.MOVEMENTS)) {
      localStorage.setItem(STORAGE_KEYS.MOVEMENTS, JSON.stringify(INITIAL_MOVEMENTS));
    }
    if (!localStorage.getItem(STORAGE_KEYS.DISTRIBUTIONS)) {
      localStorage.setItem(STORAGE_KEYS.DISTRIBUTIONS, JSON.stringify(INITIAL_DISTRIBUTIONS));
    }
    if (!localStorage.getItem(STORAGE_KEYS.AUDITS)) {
      localStorage.setItem(STORAGE_KEYS.AUDITS, JSON.stringify([]));
    }
  },`,
  `  init() {
    const current = localStorage.getItem(STORAGE_KEYS.PRODUCTS);
    if (!current || JSON.parse(current).length < 20) {
      localStorage.setItem(STORAGE_KEYS.PRODUCTS, JSON.stringify(INITIAL_PRODUCTS));
      localStorage.setItem(STORAGE_KEYS.MOVEMENTS, JSON.stringify(INITIAL_MOVEMENTS));
      localStorage.setItem(STORAGE_KEYS.DISTRIBUTIONS, JSON.stringify([]));
      localStorage.setItem(STORAGE_KEYS.AUDITS, JSON.stringify([]));
    } else {
      // Backwards compatibility check for products missing productionTarget field
      const currentProds = JSON.parse(current);
      let changed = false;
      const updatedProds = currentProds.map(p => {
        const expectedTarget = INITIAL_PRODUCTS.find(ip => ip.name === p.name)?.productionTarget || 0;
        if (expectedTarget > 0 && !p.productionTarget) {
          changed = true;
          return { ...p, productionTarget: expectedTarget };
        }
        return p;
      });
      if (changed) {
        localStorage.setItem(STORAGE_KEYS.PRODUCTS, JSON.stringify(updatedProds));
      }
    }
    if (!localStorage.getItem(STORAGE_KEYS.MOVEMENTS)) {
      localStorage.setItem(STORAGE_KEYS.MOVEMENTS, JSON.stringify(INITIAL_MOVEMENTS));
    }
    if (!localStorage.getItem(STORAGE_KEYS.DISTRIBUTIONS)) {
      localStorage.setItem(STORAGE_KEYS.DISTRIBUTIONS, JSON.stringify([]));
    }
    if (!localStorage.getItem(STORAGE_KEYS.AUDITS)) {
      localStorage.setItem(STORAGE_KEYS.AUDITS, JSON.stringify([]));
    }
  },`
);

fs.writeFileSync(mockDbPath, mockDbContent);
console.log('Successfully updated mockDb.ts with 222 items and production targets.');
